import pymysql
import time
import subprocess
import datetime
import os
import logging
import json

# Configuration
DB_HOST = "127.0.0.1"
DB_USER = "db_username"
DB_PASS = "db_password"
DB_NAME = "log4om2"

# You MUST update this to exactly match your TQSL Station Location name
TQSL_STATION_LOCATION = "YOUR_STATION_LOCATION_HERE"

# TQSL Executable path (adjust if not in system PATH)
TQSL_PATH = "tqsl"

# How often to check for new contacts (in seconds)
CHECK_INTERVAL = 3600

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def get_db_connection():
    return pymysql.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASS,
        database=DB_NAME,
        cursorclass=pymysql.cursors.DictCursor
    )

def fetch_unuploaded_contacts(conn):
    unuploaded = []
    with conn.cursor() as cursor:
        # We fetch all contacts that do not have a LOTW "Yes" or "Requested" in the text block
        # Then we strictly verify it in python.
        sql = "SELECT * FROM log WHERE qsoconfirmations NOT LIKE '%\"CT\":\"LOTW\",\"S\":\"Yes\"%' AND qsoconfirmations NOT LIKE '%\"CT\":\"LOTW\",\"S\":\"Requested\"%'"
        cursor.execute(sql)
        results = cursor.fetchall()
        
        for row in results:
            conf_str = row.get('qsoconfirmations')
            if not conf_str:
                unuploaded.append(row)
                continue
                
            try:
                confs = json.loads(conf_str)
                is_uploaded = False
                for c in confs:
                    if c.get("CT") == "LOTW" and c.get("S") in ["Yes", "Requested", "Y"]:
                        is_uploaded = True
                        break
                
                if not is_uploaded:
                    unuploaded.append(row)
            except json.JSONDecodeError:
                pass
                
    return unuploaded

def format_adif_field(field_name, data):
    if data is None:
        return ""
    data_str = str(data)
    return f"<{field_name}:{len(data_str)}>{data_str} "

def generate_adif_file(contacts, filename="temp.adi"):
    with open(filename, 'w') as f:
        f.write("Generated by Auto LOTW Sync\n<eoh>\n")
        
        for row in contacts:
            adif_record = ""
            
            call_val = row.get('callsign') or row.get('call') or row.get('CALL')
            if call_val: adif_record += format_adif_field('CALL', call_val)
            
            date_val = row.get('qsodate') or row.get('qso_date')
            if date_val: 
                if isinstance(date_val, datetime.date) or isinstance(date_val, datetime.datetime):
                    date_str = date_val.strftime("%Y%m%d")
                    time_str = date_val.strftime("%H%M%S")
                else:
                    date_str = str(date_val).replace("-", "")[:8]
                    parts = str(date_val).split()
                    time_str = parts[1].replace(":", "")[:6] if len(parts) > 1 else "000000"
                    
                adif_record += format_adif_field('QSO_DATE', date_str)
                adif_record += format_adif_field('TIME_ON', time_str)
            
            if row.get('band'): adif_record += format_adif_field('BAND', row['band'])
            if row.get('mode'): adif_record += format_adif_field('MODE', row['mode'])
            if row.get('freq'): adif_record += format_adif_field('FREQ', row['freq'])
            if row.get('rstsent'): adif_record += format_adif_field('RST_SENT', row['rstsent'])
            if row.get('rstrcvd'): adif_record += format_adif_field('RST_RCVD', row['rstrcvd'])
            if row.get('gridsquare'): adif_record += format_adif_field('GRIDSQUARE', row['gridsquare'])
            
            adif_record += "<eor>\n"
            f.write(adif_record)

def update_qsoconfirmations_json(conf_str, now_utc):
    if not conf_str:
        # If no confirmations object exists at all
        return json.dumps([{"CT":"LOTW","S":"Yes","R":"No","SV":"Electronic","RV":"Electronic","SD":now_utc}], separators=(',', ':'))
        
    try:
        confs = json.loads(conf_str)
        found_lotw = False
        for c in confs:
            if c.get("CT") == "LOTW":
                c["S"] = "Yes"
                c["SD"] = now_utc
                found_lotw = True
                break
        
        if not found_lotw:
            confs.append({"CT":"LOTW","S":"Yes","R":"No","SV":"Electronic","RV":"Electronic","SD":now_utc})
            
        return json.dumps(confs, separators=(',', ':'))
    except json.JSONDecodeError:
        return conf_str

def mark_contacts_uploaded(conn, contacts):
    if not contacts:
        return
    
    with conn.cursor() as cursor:
        now_utc = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
        sql = "UPDATE log SET qsoconfirmations = %s WHERE callsign = %s AND band = %s AND mode = %s AND qsodate = %s"
        
        update_data = []
        for c in contacts:
            if c.get('callsign') and c.get('band') and c.get('mode') and c.get('qsodate'):
                new_json = update_qsoconfirmations_json(c.get('qsoconfirmations'), now_utc)
                update_data.append((new_json, c.get('callsign'), c.get('band'), c.get('mode'), c.get('qsodate')))
                
        if update_data:
            cursor.executemany(sql, update_data)
    conn.commit()

def run_sync():
    logging.info("Starting LOTW sync check...")
    conn = None
    try:
        conn = get_db_connection()
        contacts = fetch_unuploaded_contacts(conn)
        
        if not contacts:
            logging.info("No new contacts to upload.")
            return

        logging.info(f"Found {len(contacts)} new contacts. Generating ADIF...")
        adif_filename = "upload_temp.adi"
        generate_adif_file(contacts, adif_filename)
        
        logging.info("Uploading via TQSL...")
        result = subprocess.run(
            [TQSL_PATH, "-q", "-d", "-l", TQSL_STATION_LOCATION, "-u", "-a", "compliant", "-x", adif_filename],
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            logging.info("Upload successful. Updating database...")
            mark_contacts_uploaded(conn, contacts)
        else:
            logging.error(f"TQSL upload failed with return code {result.returncode}.")
            logging.error(f"TQSL Output: {result.stdout}\n{result.stderr}")
            
    except Exception as e:
        logging.error(f"An error occurred during sync: {e}")
    finally:
        if conn:
            conn.close()
        if os.path.exists("upload_temp.adi"):
            try:
                os.remove("upload_temp.adi")
            except OSError:
                pass

if __name__ == "__main__":
    logging.info("LOTW Sync Triggered.")
    run_sync()
